### ISSUE TITLE
Dependency handling not working correctly

### ISSUE THREAD

**Issue by uubk** [uubk/scinit#8]
Dependencies are not handled correctly, that is, dependant processes are started too early:

### Configuration
```
programs:
  - type: oneshot
    before:
      - nginx
      - haproxy
      - log_forwarder
      - mailman
    path: /app/start.sh
    name: setup-script
    uid: 0
    gid: 0
  - user: root
    args:
      - -g
      - daemon off;
    path: /usr/sbin/nginx
    type: simple
    name: nginx
    group: root
  - group: root
    path: /usr/sbin/haproxy
    type: simple
    user: root
    args:
      - -f
      - /etc/haproxy/haproxy.cfg
    name: haproxy
  - path: /usr/bin/tail
    type: simple
    group: root
    user: root
    args:
      - -f
      - /opt/mailman/log
    name: log_forwarder
  - path: /usr/local/bin/master
    user: root
    group: root
    args:
      - --force
      - -C
      - /etc/mailman.cfg
    name: mailman
    type: simple
```
### Log Output:
```
[scinit] [15:25:03.516] [info] Config loaded
[scinit] [15:25:03.516] [debug] Proc nginx: Adding new dependency on proc 0
[scinit] [15:25:03.516] [debug] Proc haproxy: Adding new dependency on proc 0
[scinit] [15:25:03.516] [debug] Proc log_forwarder: Adding new dependency on proc 0
[scinit] [15:25:03.516] [debug] Proc mailman: Adding new dependency on proc 0
[scinit] [15:25:03.516] [debug] Proc setup-script: Transition to ready
[scinit] [15:25:03.516] [info] Starting: setup-script
[scinit] [15:25:03.535] [info] Child pid: 8
[scinit] [15:25:03.535] [info] Starting: nginx
[scinit] [15:25:03.554] [info] Child pid: 19
[scinit] [15:25:03.554] [info] Starting: haproxy
[scinit] [15:25:03.571] [info] Child pid: 28
[scinit] [15:25:03.571] [info] Starting: log_forwarder
[scinit] [15:25:03.593] [info] Child pid: 43
[scinit] [15:25:03.593] [info] Starting: mailman
[scinit] [15:25:03.608] [info] Child pid: 44
[scinit] [15:25:03.609] [info] Starting: info
[scinit] [15:25:03.627] [info] Child pid: 52
[scinit] [15:25:03.627] [debug] Entering main event loop
[scinit] [15:25:03.627] [debug] Epoll got back, num_fds: 5
[scinit] [15:25:03.627] [warning] Child haproxy (PID 28) exitted with RC 256
[scinit] [15:25:03.627] [debug] Event: 16
[scinit] [15:25:03.627] [debug] Child process has closed control terminal (SIGHUP)!
[scinit] [15:25:03.627] [debug] Event: 17
[haproxy] [15:25:03.627] [ALERT] 234/152503 (28) : parsing [/etc/haproxy/haproxy.cfg:35] : 'bind' : missing port number: ':::${RUNTIME_LMTP_PORT}'
```
