### ISSUE TITLE
Signal forwarding not working

### ISSUE THREAD

**Issue by uubk** [uubk/scinit#9]
Signal forwarding does not seem to take into account that processes might already have crashed:
### Configuration:
```
programs:
  - type: oneshot
    before:
      - nginx
      - haproxy
      - log_forwarder
      - mailman
    path: /app/start.sh
    name: setup-script
    uid: 0
    gid: 0
  - user: root
    args:
      - -g
      - daemon off;
    path: /usr/sbin/nginx
    type: simple
    name: nginx
    group: root
  - group: root
    path: /usr/sbin/haproxy
    type: simple
    user: root
    args:
      - -f
      - /etc/haproxy/haproxy.cfg
    name: haproxy
  - path: /usr/bin/tail
    type: simple
    group: root
    user: root
    args:
      - -f
      - /opt/mailman/log
    name: log_forwarder
  - path: /usr/local/bin/master
    user: root
    group: root
    args:
      - --force
      - -C
      - /etc/mailman.cfg
    name: mailman
    type: simple
```
### Log Output:
```
[scinit] [15:25:03.516] [info] Config loaded
[scinit] [15:25:03.516] [debug] Proc nginx: Adding new dependency on proc 0
...
[scinit] [15:25:03.633] [info] Child info (PID 52) exitted with RC 0
...
[scinit] [15:25:03.661] [info] Child setup-script (PID 8) exitted with RC 0
...
[scinit] [15:25:05.112] [warning] Child mailman (PID 44) exitted with RC 256
...
[scinit] [15:23:53.558] [debug] Forwarding signal 2 to pid 9
[scinit] [15:23:53.558] [debug] Forwarding signal 2 to pid 14
[scinit] [15:23:53.558] [debug] Forwarding signal 2 to pid 31
[scinit] [15:23:53.558] [debug] Forwarding signal 2 to pid 44
[scinit] [15:23:53.558] [debug] Forwarding signal 2 to pid 45
[scinit] [15:23:53.558] [debug] Forwarding signal 2 to pid 53
[scinit] [15:23:53.558] [warning] Received SIGTERM/SIGQUIT, stopping all children
```
Notice that the signal is not forwarded to PIDs 8 and 52 but to 44, which points to crashing processes not being unregistered correctly.
